=== qualieffort/abax-xbrl-cnbv/AbaxXBRLWeb/resources/System/Localizer.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--
Project: UBmatrix Processing Engine
Version: 3.5.0
Date:    6-15-2009

Software Copyright (c) 2002-2009 UBmatrix, Inc., All Rights Reserved
-->

<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2001/xml.xsd"/>
	<xs:element name="localization">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element name="uri" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="LocalizedString" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute ref="xml:lang" use="required"/>
											<xs:attribute name="group" type="xs:string" use="optional"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="Reference" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Text" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute ref="xml:lang" use="required"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										<xs:element name="Uri" type="xs:string" minOccurs="0"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="locale" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="LocalizedString" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute ref="xml:lang" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="UniqueMemoID">
			<xs:selector xpath=".//*"/>
			<xs:field xpath="@id"/>
		</xs:unique>
	</xs:element>
</xs:schema>

<!--
The contents of this file are subject to the End-User Software License Agreement (the "License"). You may not use this 
file except in compliance with the License. A current copy of the License is available by contacting product support.

Software distributed under the License is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or 
implied. See the License for the specific language governing rights and limitations under the License.
-->

=== qualieffort/abax-xbrl-cnbv/AbaxXBRLCore/coreroot/resources/System/InlineLocalizer.xml
<?xml version="1.0" encoding="utf-8"?> 

<!--
    * Constants for Inline XBRL memos
-->

<!DOCTYPE InlneLocalizer [

<!-- Used to control the base location of specifications anchors -->

<!ENTITY UBmatrix                "http://docs.ubmatrix.com">
<!ENTITY InlineXBRLSpecUri       "http://www.xbrl.org/Specification/inlineXBRL-part1/REC-2010-04-20/inlineXBRL-part1-REC-2010-04-20+corrected-errata-2011-08-17.html">
<!ENTITY InlineXBRLSpecUri1-1    "http://www.xbrl.org/specification/inlinexbrl-part1/rec-2013-11-18/inlinexbrl-part1-rec-2013-11-18.html">
<!ENTITY XBRLSpecUri             "http://www.xbrl.org/Specification/XBRL-2.1/REC-2003-12-31/XBRL-2.1-REC-2003-12-31+corrected-errata-2013-02-20.html">
<!ENTITY XBRLDimensionSpecUri    "http://www.xbrl.org/specification/dimensions/rec-2012-01-25/dimensions-rec-2006-09-18+corrected-errata-2012-01-25-clean.html">

]>

<localization xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Localizer.xsd">

    <!-- Inline 1.0 messages -->

    <!--
        * Numeric fact has both decimals and precision attributes.
        * <br/><br/>
        * Particles<br/>
        * <ol>
        * <li>fact QName</li>
        * <li>document name</li>
        * <li>line number</li>
        * <li>column number</li>
        * <li>value</li>
        * </ol>
    -->
    <!-- c_DecimalsAndPrecision -->
    <uri id="memo://ubmatrix.com/Xbrl/InlineXBRL#DecimalsAndPrecision">
        <LocalizedString xml:lang="en">Inline XBRL: Fact {0} in document {1} at line {2}, column {3}, with value {4} has both decimals and precsion attributes.</LocalizedString>
        <Reference>
            <Text xml:lang="en">For more information, see Inline XBRL documentation.</Text>
            <Uri>&InlineXBRLSpecUri;#d1e5078</Uri>
        </Reference>
    </uri>


    <!--
        * Duplicate arc role detected - usually informational.
        * <br/><br/>
        * Particles<br/>
        * <ol>
        * <li>QName</li>
        * <li>document name</li>
        * <li>line number</li>
        * <li>column number</li>
        * <li>href value</li>
        * <li>existing document name</li>
        * <li>existing line number</li>
        * <li>existing column number</li>
        * </ol>
        *
    -->
    <!-- c_DuplicateArcRole -->
    <uri id="memo://ubmatrix.com/Xbrl/InlineXBRL#DuplicateArcRole">
        <LocalizedString xml:lang="en">Inline XBRL: Duplicate Arc Role definition detected in document {1} at line {2}, column {3} with value {4}. Existing definition in document {5} at line {6}, column {7}.</LocalizedString>
        <Reference>
            <Text xml:lang="en">For more information, see Inline XBRL documentation.</Text>
            <Uri>&InlineXBRLSpecUri;#d1e7450</Uri>
        </Reference>
    </uri>

    <!--
     * Duplicate context defintion.
     * <br/><br/>
     * Particles<br/>
     * <ol>
     * <li>QName</id>
     * <li>document name</li>
     * <li>line number</li>
     * <li>column number</li>
     * <li>id</li>
     * <li>existing document name</li>
     * <li>existing line number</li>
     * <li>existing column number</li>
     * </ol>
     -->
    <!-- c_DuplicateContext -->
    <uri id="memo://ubmatrix.com/Xbrl/InlineXBRL#DuplicateContext">
        <LocalizedString xml:lang="en">Inline XBRL: Duplicate Context definition detected in document {1} at line {2}, column {3} with value {4}. Existing definition in document {5} at line {6}, column {7}.</LocalizedString>
        <Reference>
            <Text xml:lang="en">For more information, see Inline XBRL documentation.</Text>
            <Uri>&InlineXBRLSpecUri;#d1e7450</Uri>
        </Reference>
    </uri>

    <!--
     * Duplicate fact - same information specified as a fact elsewhere.
     * <br/><br/>
     * Particles<br/>
     * <ol>
     * <li>QName</li>
     * <li>document name</li>
     * <li>line number</li>
     * <li>column number</li>
     * <li>context</li>
     * <li>value</li>
     * <li>existing document name</li>
     * <li>existing fact line number</li>
     * <li>existing fact column number</li>
     * <li>existing fact context</li>
     * <li>existing fact value</li>
     * </ol>
     -->
    <!-- c_DuplicateFact -->
    <uri id="memo://ubmatrix.com/Xbrl/InlineXBRL#DuplicateFact">
        <LocalizedString xml:lang="en">Inline XBRL: Duplicate fact definition detected for {0} in document {1} at line {2}, column {3} with context {4} and value {5}. Existing definition in document {6} at line {7}, column {8} with context {9} and value {10}.</LocalizedString>
        <Reference>
            <Text xml:lang="en">For more information, see Inline XBRL documentation.</Text>
            <Uri>&InlineXBRLSpecUri;#d1e7704</Uri>
        </Reference>
    </uri>

    <!--
        * Duplicate fact removed - same information specified as a fact elsewhere.
        * <br/><br/>
        * Particles<br/>
        * <ol>
        * <li>QName</li>
        * <li>document name</li>
        * <li>line number</li>
        * <li>column number</li>
        * <li>context</li>
        * <li>value</li>
        * <li>existing document name</li>
        * <li>existing fact line number</li>
        * <li>existing fact column number</li>
        * <li>existing fact context</li>
        * <li>existing fact value</li>
        * </ol>
    -->
    <!-- c_DuplicateFactRemoved -->
    <uri id="memo://ubmatrix.com/Xbrl/InlineXBRL#DuplicateFactRemoved">
        <LocalizedString xml:lang="en">Inline XBRL: Duplicate fact definition removed for {0} in document {1} at line {2}, column {3} with context {4} and value {5}. Existing definition in document {6} at line {7}, column {8} with context {9} and value {10} has been retained.</LocalizedString>
        <Reference>
            <Text xml:lang="en">For more information, see Inline XBRL documentation.</Text>
            <Uri>&InlineXBRLSpecUri;#d1e7704</Uri>
        </Reference>
    </uri>
    
    <!--
        * Duplicate fraction element - bad nesting of tags.
        * Will always be in the same document.
        * <br/><br/>
        * Particles<br/>
        * <ol>
        * <li>QName</li>
        * <li>document name</li>
        * <li>line number</li>
        * <li>column number</li>
        * <li>existing fact line number</li>
        * <li>existing fact column number</li>
        * </ol>
    -->
    <!-- c_DuplicateFractionElement -->
    <uri id="memo://ubmatrix.com/Xbrl/InlineXBRL#DuplicateFractionElement">
        <LocalizedString xml:lang="en">Inline XBRL: Duplicate fraction element detected for {0} in document {1} at line {2}, column {3}. Existing definition at line {4}, column {5}.</LocalizedString>
        <Reference>
            <Text xml:lang="en">For more information, see Inline XBRL documentation.</Text>
            <Uri>&InlineXBRLSpecUri;#d1e3013</Uri>
        </Reference>
    </uri>
    
    <!--
     * Duplicate footnote definition.
     * <br/><br/>
     * Particles<br/>
     * <ol>
     * <li>QName</li>
     * <li>document name</li>
     * <li>line number</li>
     * <li>column number</li>
     * <li>footnote id</li>
     * <li>existing document name</li>
     * <li>existing footnote line number</li>
     * <li>existing footnote column number</li>
     * </ol>
     -->
    <!-- c_DuplicateFootnote -->
    <uri id="memo://ubmatrix.com/Xbrl/InlineXBRL#DuplicateFootnote">
        <LocalizedString xml:lang="en">Inline XBRL: Duplicate footnote definition detected in document {1} at line {2}, column {3} with id={4}. Existing definition in document {5} at line {6}, column {7}.</LocalizedString>
        <Reference>
            <Text xml:lang="en">For more information, see Inline XBRL documentation.</Text>
            <Uri>&InlineXBRLSpecUri;#d1e1791</Uri>
        </Reference>
    </uri>

    <!--
        * Duplicate value for element id.
        * <br/><br/>
        * Particles<br/>
        * <ol>
        * <li>QName</li>
        * <li>document name</li>
        * <li>line number</li>
        * <li>column number</li>
        * <li>element id</li>
        * <li>existing document name</li>
        * <li>existing element line number</li>
        * <li>existing element column number</li>
        * <li>existing element QName</li>
        * </ol>
    -->
    <!-- c_DuplicateId -->
    <uri id="memo://ubmatrix.com/Xbrl/InlineXBRL#DuplicateId">
        <LocalizedString xml:lang="en">Inline XBRL: Duplicate id detected for element {0} in document {1} at line {2}, column {3} with id={4}. Existing definition in document {5} at line {6}, column {7} on element {8}.</LocalizedString>
        <Reference>
            <Text xml:lang="en">For more information, see Inline XBRL documentation.</Text>
            <Uri>&InlineXBRLSpecUri;#dle5181</Uri>
        </Reference>
    </uri>

    <!--
        * Duplicate linkbase definition - usually informational.
        * <br/><br/>
        * Particles<br/>
        * <ol>
        * <li>QName</li>
        * <li>document name</li>
        * <li>line number</li>
        * <li>column number</li>
        * <li>existing href</li>
        * <li>existing document name</li>
        * <li>existing line number</li>
        * <li>existing column number</li>
        * </ol>
    -->
    <!-- c_DuplicateLinkbaseRef -->
    <uri id="memo://ubmatrix.com/Xbrl/InlineXBRL#DuplicateLinkbaseRef">
        <LocalizedString xml:lang="en">Inline XBRL: Duplicate Linkbase reference detected in document {1} at line {2}, column {3} with value {4}. Existing definition in document {5} at line {6}, column {7}.</LocalizedString>
        <Reference>
            <Text xml:lang="en">For more information, see Inline XBRL documentation.</Text>
            <Uri>&InlineXBRLSpecUri;#d1e6819</Uri>
        </Reference>
    </uri>

    <!--
